FROM python:3.10-slim-bullseye

WORKDIR /apps

COPY requirements.txt .

RUN apt-get update && apt-get -y --no-install-recommends \
    install libpq-dev \
    procps \
    gcc \
    python3-dev \ 
    && pip3 install --no-cache-dir -r requirements.txt \
    && apt-get remove -y gcc  python3-dev \
    && apt-get purge -y --auto-remove \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


COPY ./AGISERVER/ ./
CMD [ "bash" ]
# CMD ["python3", "/apps/Agiserver/core/main.py", "host=0.0.0.0"]

